Hotel_Management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('hotel.urls')),
    path('', include('myadmin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from hotel import views

app_name='hotel'

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name="index"),
    path('about/', views.AboutTemplateView.as_view(), name="about"),
    path('ourroom/', views.OurRoomTemplateView.as_view(), name="ourroom"),
    path('gallery/', views.GalleryTemplateView.as_view(), name="gallery"),
    path('blog/', views.BlogTemplateView.as_view(), name="blog"),
    path('contact/', views.ContactUsTemplateView.as_view(), name="contact"),
    path('customerprofile/<int:pk>', views.CustomerProfileDetailView.as_view(), name="customerprofile"),
    path('updateprofile/<int:pk>', views.CustomerProfileUpdateView.as_view(), name="updateprofile"),
    path('room/', views.RoomImageListView.as_view(), name="room"),
    path('roomdetail/<int:pk>', views.RoomDetailView.as_view(), name="roomdetail"),
    path('bookingroom/<int:id>', views.BookingCreateView.as_view(), name="bookingroom"),
    path('bookinglist/', views.BookingListView.as_view(), name="bookinglist"),
    path('bookingcancel/', views.BookingCancelView.as_view(), name="bookingcancel"),
    path('bookingpayment/<int:pk>', views.PaymentCreateView.as_view(), name="bookingpayment"),
    path('bookinginvoice/<int:pk>', views.BookingInvoiceList.as_view(), name="bookinginvoice"),
    path('generatepdf/<int:pk>', views.GeneratePdf.as_view(), name="generatepdf"),
    #path('roomsearch/', views.RoomSearchView.as_view(), name="roomsearch"),
]

myadmin/urls.py
from django.urls import path
from myadmin import views


app_name="myadmin"

urlpatterns = [
    path('myadmin/', views.IndexTemplateView.as_view(), name="myadmin"),
    path('profile/<int:pk>', views.AdminProfile.as_view(), name="profile"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('userlogin/', views.UserLogin.as_view(), name="userlogin"),
    path('userlogout/', views.Logout.as_view(), name="userlogout"),
    path('addroom/', views.AdminRoomCreate.as_view(), name="addroom"),
    path('roomlist/', views.AdminRoomList.as_view(), name="roomlist"),
    path('updateroom/<int:pk>', views.AdminRoomUpdateView.as_view(), name="updateroom"),
    path('deleteroom/<int:pk>', views.AdminRoomDeleteView.as_view(), name="deleteroom"),
    path('customerlist/', views.AdminCustomerListView.as_view(), name="customerlist"),
    path('customerupdate/<int:pk>', views.AdmincustomerUpdateView.as_view(), name="customerupdate"),
    path('customerdelete/<int:pk>', views.AdminCustomerDeleteView.as_view(), name="customerdelete"),
    path('adminbookinglist/', views.AdminBookingList.as_view(), name="adminbookinglist"),
    path('admininvoice/', views.AdminBookingInvoiceList.as_view(), name="admininvoice"),
]

hotel/models.py
from django.db import models
from hotel.modelmanager import BaseModel
from datetime import datetime
from django.core.validators import MinValueValidator
from myadmin.models import *
import random
# Create your models here.

class Room(BaseModel):
    FREE_BREAKFAST = "FREEBREAKFAST"
    FREE_LUNCH = "FREE LUNCH"
    FREE_DINNER = "FREE DINNER"
    FREE_BREAKFAST_AND_DINNER = "FREE BREAKFAST AND DINNER"
    FREE_WELCOME_DRINK = "FREE WELCOME DRINK"
    NO_FREE_FOOD = "NO FREE FOOD"

    FOOD_CATEGORIES = (
        ('FREE BREAKFAST', FREE_BREAKFAST),
        ('FREE LUNCH', FREE_LUNCH),
        ('FREE DINNER', FREE_DINNER),
        ('FREE BREAKFAST AND DINNER', FREE_BREAKFAST_AND_DINNER),
        ('FREE WELCOME DRINK', FREE_WELCOME_DRINK),
        ('NO FREE FOOD', NO_FREE_FOOD)
    )

    PREMIUM_ROOM = "PREMIUM ROOM"
    PRESIDENTIAL_SUITE_POOL_VIEW = "PRESIDENTIAL SUITE POOL VIEW"
    DELUXE = "DELUXE"
    KING = "KING"
    LUXURY = "LUXURY"
    SUPERIOR = "SUPERIOR"

    ROOM_CATEGORIES = (
        ('PREMIUM_ROOM', PREMIUM_ROOM),
        ('PRESIDENTIAL SUITE POOL VIEW', PRESIDENTIAL_SUITE_POOL_VIEW),
        ('DELUXE', DELUXE),
        ('KING', KING),
        ('LUXURY', LUXURY),
        ('SUPERIOR', SUPERIOR)
    )

    KING = "KING"
    TWIN = "TWIN"
    QUEEN = "QUEEN"

    BED_CATEGORIES = (
        ('KING', KING),
        ('TWIN', TWIN),
        ('QUEEN', QUEEN)
    )

    AC_ROOM = "AC ROOM"
    NON_AC_ROOM = 'NON AC ROOM'

    ROOM_STOCK = (
        ('AC ROOM', AC_ROOM),
        ('NON AC ROOM', NON_AC_ROOM)
    )

    room_stock = models.CharField(max_length=50, choices=ROOM_STOCK)
    food_categgories = models.CharField(max_length=50, choices=FOOD_CATEGORIES)
    room_price = models.FloatField()
    #room_image = models.ImageField(upload_to='upload/', max_length=255, null=True, default=None)
    room_no = models.IntegerField()
    room_categories = models.CharField(max_length=30, choices=ROOM_CATEGORIES)
    bed_categories = models.CharField(max_length=20, choices=BED_CATEGORIES)
    capacity = models.IntegerField(validators=[MinValueValidator(1)]) 
    #is_available = models.CharField(max_length=30, default=True)
    


class RoomImage(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="roomimage")
    image = models.FileField(upload_to='upload/', max_length=255, null=True, default=None)


class Booking(BaseModel):
    #date = models.DateField(null=True, default=datetime.now)
    check_in = models.DateField(null=True, default=datetime.now)
    check_out = models.DateField(null=True, default=datetime.now)

    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"

    BOOKING_STATUS = (
        ('CONFIRMED', CONFIRMED),
        ("CANCELLED", CANCELLED)
    )

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="room_booking")
    total_members = models.IntegerField()
    booking_status = models.CharField(max_length=50, choices=BOOKING_STATUS)
    total_days = models.IntegerField(null=True)
    no_of_room = models.IntegerField()
    #total_amount = models. FloatField(null=True)
    #is_active = models.BooleanField(default=True)


    
class Payment(BaseModel):
    CARD = "CARD"
    CASH = "CASH"
    PAYTM = "PAYTM"

    PAYMENT_TYPE = {
        ('CARD', CARD),
        ('CASH', CASH),
        ('PAYTM', PAYTM),
    }

    payemnt_type = models.CharField(max_length=30, choices=PAYMENT_TYPE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=15, decimal_places=2)
    order_id = models.IntegerField(unique=True, null=True, default=None)
    made_on = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.order_id:
            self.order_id = random.randint(1000, 9999)
        super().save(*args, **kwargs)

hotel/forms.py
from django import forms
from .models import *


class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = [
            'check_in',
            'check_out',
            'total_members',
            'total_days',
            'no_of_room',
        ]


class BookingPaymentForm(forms.ModelForm):
    class Meta:
         model = Payment
         fields = [
            'payemnt_type',
            'total_amount',
         ]

    def __init__(self, **kwargs):
        booking_id = kwargs.pop("booking_id")
        super().__init__(**kwargs)
        booking_obj = Booking.objects.get(id=booking_id)
        self.fields["total_amount"].initial = booking_obj.total_days * booking_obj.no_of_room * booking_obj.room.room_price

hotel/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, UpdateView, CreateView, DetailView, DeleteView, ListView, View
from .models import *
from .forms import *
from myadmin.forms import *
from django.contrib import messages
import json
from datetime import timedelta
from django.http import JsonResponse
from hotel.service.mails import HotelBookedEmailSender
from hotel.utils import render_to_pdf
from math import ceil
from django.db.models import Sum
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q



# Create your views here.

#----------------------Index Template Starts from here-------------------------------->

class IndexTemplateView(TemplateView):
    template_name = 'hotel/index.html'


#----------------------------About Template Starts from here---------------------------->

class AboutTemplateView(TemplateView):
    template_name = 'hotel/about.html'

#------------------------------Our Room Template Starts from here------------------------->

class OurRoomTemplateView(TemplateView):
    template_name = 'hotel/our-room.html'

#------------------------------Gallery Template View Starts from here----------------------->

class GalleryTemplateView(TemplateView):
    template_name = 'hotel/gallery.html'

#----------------------------------Blog Template View Starts from here---------------------->

class BlogTemplateView(TemplateView):
    template_name = 'hotel/blog.html'

#---------------------------------Contact Template View Starts from here-------------------->

class ContactUsTemplateView(TemplateView):
    template_name = 'hotel/contact-us.html'

#<--------------------------------------------Customer Profile View Starts From here----------------------->

class CustomerProfileDetailView(DetailView):
    model = User
    template_name = 'hotel/customerprofile.html'


#<----------------------------------------------Customer Update Profile View Starts from here----------------------->

class CustomerProfileUpdateView(UpdateView):
    model = User
    form_class = AdminProfileForm
    template_name = 'hotel/updateprofile.html'
    success_url = reverse_lazy('hotel:customerprofile')

#<----------------------------------------------Room Image List View Starts from here----------------------------->

class RoomImageListView(ListView):
    model = Room
    template_name = 'hotel/roomimagelist.html'

    def get(self, request):
        check_in = request.GET.get("check_in")
        check_out = request.GET.get("check_out")
        total_members = request.GET.get("total_members")

        if  check_in == None or check_out == None:
            return render(request, self.template_name)

        unavailable_rooms = Room.objects.filter(room_booking__booking_status=Booking.CONFIRMED).filter(Q(room_booking__check_in__lte=check_out, room_booking__check_out__gte=check_in) | Q(room_booking__check_in__gte=check_in, room_booking__check_out__lte=check_out))

        booked_room_ids = unavailable_rooms.values_list('id', flat=True)

        available_rooms = Room.objects.exclude(id__in = booked_room_ids)

        return render(request, self.template_name, {"available_rooms": available_rooms, "check_in": check_in, "check_out": check_out, "total_members": total_members})
    

#<---------------------------------------------------Room Detail View Starts from here------------------------------> 

class RoomDetailView(DetailView):
    model = Room
    template_name = 'hotel/roomdetail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = self.kwargs
        room_id = data["pk"]
        post = RoomImage.objects.filter(room=room_id) 
        context["post"] = post
        context["check_in"] = self.request.GET["check_in"]
        context["check_out"] = self.request.GET["check_out"]
        context["total_members"] = self.request.GET["total_members"]
        room = Room.objects.get(id=room_id)
        no_of_room = int(context["total_members"])/int(room.capacity)
        context["no_of_room"] = ceil(no_of_room)
        room_price = room.room_price
        total_room_price = int(room_price) * int(context["no_of_room"])
        context["total_room_price"] = total_room_price
        return context
    

#<-----------------------------------Booking Create View Starts from here---------------------------------->

class BookingCreateView(CreateView):
    form_class = BookingForm
    template_name = 'hotel/bookingroom.html'
    #success_url = reverse_lazy('hotel:bookingpayment')

    def form_valid(self, form):
        booking = form.save(commit=False)
        room = Room.objects.get(id=self.kwargs['id'])
        booking.room = room
        booking.user = self.request.user
        booking.save()
        room.is_available = False
        room.save()
        return redirect(reverse("hotel:bookingpayment", kwargs={"pk":booking.id}))

  

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        data = self.kwargs
        room_id = data['id']
        room_data = Room.objects.get(id=room_id)
        room_image = RoomImage.objects.filter(room=room_id)
        # room_booking_dates = Booking.objects.filter(room=room_data)
        ins = self.request.GET["check_in"]
        out = self.request.GET["check_out"]
        context["check_in"] = ins
        context["check_out"]= out
        context["total_members"] = self.request.GET["total_members"]
        check_ins = datetime.strptime(ins, "%Y-%m-%d")
        check_outs = datetime.strptime(out, "%Y-%m-%d")
        days = (check_outs - check_ins).days
        context["total_days"] = days
        context["no_of_room"] = self.request.GET["no_of_room"]

        # disable_date = []
        # for booking in room_booking_dates:

        #     def daterange(date1, date2):
        #         for n in range(int ((date2 -date1).days)+1):
        #             yield date1 + timedelta(n)

        #     for dt in daterange(booking.check_in, booking.check_out):
        #         disable_date.append(dt.strftime("%d/%m/%Y"))
        # print(disable_date)

        context['room_image'] = room_image
        context['room_id'] = room_id
        context['room_data'] = room_data
        # context["disable_date"] = disable_date
        return context

#<-----------------------------------------Booking List View Starts from here----------------------------->

class BookingListView(ListView):
    model = Booking
    template_name = 'hotel/bookinglist.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user.pk
        bookings = Booking.objects.filter(user=user).annotate(total_amount=Sum('payment__total_amount'))
        # for booking in bookings:
        #     total = Payment.objects.get(user=user, booking=booking)
        #     booking.total_amount = total.total_amount
        context['post'] = bookings 
        return context
    

                                                                                                                      

#<-------------------------------------------Booking Cancel View Starts fromn here-------------------------->

class BookingCancelView(View):

     def post(self, request):
        booking_id = request.POST.get('pk')
        try:
            booking = Booking.objects.get(id=booking_id)
            if booking.booking_status == 'CONFIRMED':
                booking.booking_status = "CANCELLED"
                booking.save()
                return JsonResponse({"status": "success", "new_status": booking.booking_status})
            else:
                return JsonResponse({"status": "error", "message": "Booking cannot be cancelled."})
        except Booking.DoesNotExist:
            return JsonResponse({"status": "error", "message": "Booking not found."})
    
    

#<-----------------------------------------Payment Form Create vuew starts from here----------------------->

class PaymentCreateView(CreateView):
    model = Payment
    form_class = BookingPaymentForm
    template_name = 'hotel/bookingpayment.html'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["booking_id"] = self.kwargs["pk"]
        return kwargs

    def form_valid(self, form):
        payment = form.save(commit=False)
        booking = Booking.objects.get(pk = self.kwargs['pk'])
        payment.booking = booking
        payment.user = self.request.user
        booking.booking_status = "CONFIRMED"
        booking.save()
        payment.save()
        # messages.success(self.request, 'Payment successful !!!!')

        #<-------------Email sends Logic Starts from here-------------------->
        username = self.request.user.username
        username = username.upper()
        subject = "Booking & Payment Confirmation"
        message = "Dear customer your booking has been confirmed."
        from_email = "admin@example.com"
        to_email = [self.request.user.email]
        variable_dict = {"username": username, "message": message}
        HotelBookedEmailSender().send_email_custom(subject, from_email, to_email, variable_dict)
        return redirect(reverse("hotel:bookinginvoice", kwargs={"pk":booking.pk}))


#<-----------------------------------------------------Booking Invoice List Starts from her------------------------------------>

class BookingInvoiceList(ListView):
    model = Payment
    template_name = 'hotel/bookinginvoice.html'

    # def get_queryset(self):
    #     queryset = Payment.objects.filter(user = self.request.user)
    #     return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        id = self.kwargs['pk']
        context['object_list'] = Payment.objects.filter(booking__pk=id) 
        return context
    
    

templates/hotel/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <!-- basic -->
   <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <!-- mobile metas -->
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <meta name="viewport" content="initial-scale=1, maximum-scale=1">
   <!-- site metas -->
   <title>{% block title %} {% endblock %}</title>
   <meta name="keywords" content="">
   <meta name="description" content="">
   <meta name="author" content="">
   <!-- bootstrap css -->
   <link rel="stylesheet" href="{% static 'hotel/css/bootstrap.min.css' %}">
   <!-- style css -->
   <link rel="stylesheet" href="{% static 'hotel/css/style.css' %}">
   <!-- Responsive-->
   <link rel="stylesheet" href="{% static 'hotel/css/responsive.css' %}">
   <!-- fevicon -->
   <link rel="icon" href="{% static 'hotel/images/fevicon.png' %}" type="image/gif" />
   <!-- Scrollbar Custom CSS -->
   <link rel="stylesheet" href="{% static 'hotel/css/jquery.mCustomScrollbar.min.css' %}">
   <!-- Tweaks for older IEs-->
   {% comment %} <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
   media="screen"> {% endcomment %}
   <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
   </head>
<!-- body -->

<body class="main-layout">
   <!-- loader  -->
   <div class="loader_bg">
      <div class="loader"><img src="{% static 'hotel/images/loading.gif' %}" alt="#" /></div>
   </div>
   <!-- end loader -->
   <!-- header -->
   <header>
      <!-- header inner -->
      <div class="header">
         <div class="container">
            <div class="row">
               <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col logo_section">
                  <div class="full">
                     <div class="center-desk">
                        <div class="logo">
                           <a href="index.html"><img src="{% static 'hotel/images/Taj logo.jpg' %}"style="height:80px; width:120px; object-position: right top";></a>
                        </div>
                     </div>
                  </div>
               </div>
               <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9">
                  <nav class="navigation navbar navbar-expand-md navbar-dark ">
                     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04"
                     aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                     </button>
                     <div class="collapse navbar-collapse" id="navbarsExample04">
                        <ul class="navbar-nav mr-auto">
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'hotel:index' %}">Home</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'hotel:about' %}">About</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'hotel:ourroom' %}">Our room</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'hotel:gallery' %}">Gallery</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'hotel:blog' %}">Blog</a>
                           </li>
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'hotel:contact' %}">Contact Us</a>
                           </li>
                           {% if request.user.is_authenticated %}
                           <li class="nav-item">
                              <a class="nav-link" href="{% url 'hotel:room' %}">Book Room</a>
                              {% endif %}
                              
                              {% if request.user.is_authenticated %}
                              <li class="nav-item">
                                 <a class="nav-link" href="{% url 'hotel:bookinglist' %}">My Bookings</a>
                                 {% endif %}
                                 
                                 {% if request.user.is_authenticated %}
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'hotel:customerprofile' user.id %}">Profile</a>
                                 {% endif %}
                                 
                                 {% if request.user.is_authenticated %}
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'myadmin:userlogout' %}">Logout</a>
                                    {% else %}
                                    <li class="nav-item">
                                       <a class="nav-link" href="{% url 'myadmin:userlogin' %}">Login</a>
                                    </li>
                                 </li>
                                 <li class="nav-item">
                                    <a class="nav-link" href="{% url 'myadmin:signup' %}">SignUp</a>
                              </li>
                              {% endif %}
                        </ul>
                     </div>
                  </nav>
               </div>
            </div>
         </div>
      </div>
   </header>
   <!-- end header inner -->
   <!-- end header -->
   <!-- banner -->
   {% block content %}
   
   {% endblock %}
   <footer>
      <div class="footer">
         <div class="container">
            <div class="row">
               <div class=" col-md-4">
                  <h3>Contact US</h3>
                  <ul class="conta">
                     <li><i class="fa fa-map-marker" aria-hidden="true"></i> Address</li>
                     <li><i class="fa fa-mobile" aria-hidden="true"></i> +01 1234569540</li>
                     <li> <i class="fa fa-envelope" aria-hidden="true"></i><a href="#"> demo@gmail.com</a></li>
                  </ul>
               </div>
               <div class="col-md-4">
                  <h3>Menu Link</h3>
                  <ul class="link_menu">
                     <li class="active"><a href="#">Home</a></li>
                     <li><a href="about.html"> about</a></li>
                     <li><a href="room.html">Our Room</a></li>
                     <li><a href="gallery.html">Gallery</a></li>
                     <li><a href="blog.html">Blog</a></li>
                     <li><a href="contact.html">Contact Us</a></li>
                  </ul>
               </div>
               <div class="col-md-4">
                  <h3>News letter</h3>
                  <form class="bottom_form">
                     <input class="enter" placeholder="Enter your email" type="text" name="Enter your email">
                     <button class="sub_btn">subscribe</button>
                  </form>
                  <ul class="social_icon">
                     <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                     <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                     <li><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                     <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
                  </ul>
               </div>
            </div>
         </div>
         <div class="copyright">
            <div class="container">
               <div class="row">
                  <div class="col-md-10 offset-md-1">

                     <p>
                        © 2019 All Rights Reserved. Design by <a href="https://html.design/"> Free Html Templates</a>
                        <br><br>
                        Distributed by <a href="https://themewagon.com/" target="_blank">ThemeWagon</a>
                     </p>
                     
                  </div>
               </div>
            </div>
         </div>
      </div>
   </footer>
   <!-- end footer -->
   <!-- Javascript files-->
   <script src="{% static 'hotel/js/jquery.min.js' %}"></script>
   <script src="{% static 'hotel/js/bootstrap.bundle.min.js' %}"></script>
   <script src="{% static 'hotel/js/jquery-3.0.0.min.js' %}"></script>
   <!-- sidebar -->
   <script src="{% static 'hotel/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
   <script src="{% static 'hotel/js/custom.js' %}"></script>
</body>

</html>

templates/hotel/bookinginvoice.html
{% extends 'hotel/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Booking Invoice Page {% endblock %}
{% block content %}
<div class="back_re">
    <div class="container mt-5">
       <div class="row">
          <div class="col-md-12">
             <div class="title">
                <h2>Booking Invoice List</h2>
             </div>
          </div>
       </div>
    </div>
 </div>
 <div class="row">
    <div class="col-sm-12">
        <div class="card mt-5 mx-5">    
            <div class="card-body">
                <div class="table-responsive">
                    <strong><font face="Arial" size="5" color="black"><center><caption>Booking And Room Details:-</caption></center></font></strong>
                    <table class="table table-bordered" style="width:100%">
                        {% for invoice in object_list %}
                        <tbody>
                            {% comment %} <tr>
                                <b><font size="30"><caption>Booking Details</caption></b></font>
                                </tr> {% endcomment %}
                                <tr>
                                    <th>Invoice Number:</th>
                                    <td>{{invoice.order_id}}</td>
                                    <th>Created On:</th>
                                    <td>{{invoice.made_on}}</td>
                                    <th>Booking Id:</th>
                                    <td>{{invoice.booking.id}}</td>
                                    <th>Customer Name:</th>
                                    <td>{{invoice.user.first_name}} {{invoice.user.last_name}}</td>
                                </tr>

                                <tr>
                                    <th>Email:</th>
                                    <td>{{invoice.user.email}}</td>
                                    <th>Contact:</th>
                                    <td>{{invoice.user.phone_no}}</td>
                                    <th>Check In:</th>
                                    <td>{{invoice.booking.check_in}}</td>
                                    <th>Check Out:</th>
                                    <td>{{invoice.booking.check_out}}</td>
                                </tr>
        
                                <tr>
                                    <th>Booking Status:</th>
                                    <td>{{invoice.booking.booking_status}}</td>
                                    <th>Total Days:</th>
                                    <td>{{invoice.booking.total_days}}</td>
                                    <th>Total Members:</th>
                                    <td>{{invoice.booking.total_members}}</td>
                                    <th>No Of Rooms:</th>
                                    <td>{{invoice.booking.no_of_room}}</td>
                                </tr>
                                
                                <tr>
                                    <th></th>
                                </tr>
                                
                                <tr>
                                    <th>Room No</th>
                                    <th>Image</th>
                                    <th>Room Category</th>
                                    <th>Bed Category</th>
                                    <th>Room Stock</th>
                                    <th>Food Category</th>
                                    <th>Room Price</th>
                                    <th>Total Amount</th>
                                </tr>
                                <tr>
                                    <td>{{invoice.booking.room.room_no}}</td>
                                    <td><img src="/media/{{invoice.booking.room.roomimage.first.image}}"style="height: 70px; width: 70px; border-radius: 10px";>
                                        <td>{{invoice.booking.room.room_categories}}</td>
                                        <td>{{invoice.booking.room.bed_categories}}</td>
                                        <td>{{invoice.booking.room.room_stock}}</td>
                                        <td>{{invoice.booking.room.food_categgories}}</td>
                                        <td>{{invoice.booking.room.room_price}}</td>
                                        <td>{{invoice.total_amount}}</td>
                                    </tr>
                                </tbody>
                            </table>
                            <a href="{% url 'hotel:generatepdf' invoice.pk %}"><button type="submit" class="btn btn-info">Download Invoice</button></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>                                    
{% endblock %}