Hotel_Management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('hotel.urls')),
    path('', include('myadmin.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/urls.py
from django.urls import path
from hotel import views

app_name='hotel'

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name="index"),
    path('about/', views.AboutTemplateView.as_view(), name="about"),
    path('ourroom/', views.OurRoomTemplateView.as_view(), name="ourroom"),
    path('gallery/', views.GalleryTemplateView.as_view(), name="gallery"),
    path('blog/', views.BlogTemplateView.as_view(), name="blog"),
    path('contact/', views.ContactUsTemplateView.as_view(), name="contact"),
    path('customerprofile/<int:pk>', views.CustomerProfileDetailView.as_view(), name="customerprofile"),
    path('updateprofile/<int:pk>', views.CustomerProfileUpdateView.as_view(), name="updateprofile"),
    path('room/', views.RoomImageListView.as_view(), name="room"),
    path('roomdetail/<int:pk>', views.RoomDetailView.as_view(), name="roomdetail"),
    path('bookingroom/<int:id>', views.BookingCreateView.as_view(), name="bookingroom"),
    path('bookinglist/', views.BookingListView.as_view(), name="bookinglist"),
    path('bookingcancel/', views.BookingCancelView.as_view(), name="bookingcancel"),
    path('bookingpayment/<int:pk>', views.PaymentCreateView.as_view(), name="bookingpayment"),
    path('bookinginvoice/<int:pk>', views.BookingInvoiceList.as_view(), name="bookinginvoice"),
    path('generatepdf/<int:pk>', views.GeneratePdf.as_view(), name="generatepdf"),
    #path('roomsearch/', views.RoomSearchView.as_view(), name="roomsearch"),
]

myadmin/urls.py
from django.urls import path
from myadmin import views


app_name="myadmin"

urlpatterns = [
    path('myadmin/', views.IndexTemplateView.as_view(), name="myadmin"),
    path('profile/<int:pk>', views.AdminProfile.as_view(), name="profile"),
    path('signup/', views.SignUpView.as_view(), name="signup"),
    path('userlogin/', views.UserLogin.as_view(), name="userlogin"),
    path('userlogout/', views.Logout.as_view(), name="userlogout"),
    path('addroom/', views.AdminRoomCreate.as_view(), name="addroom"),
    path('roomlist/', views.AdminRoomList.as_view(), name="roomlist"),
    path('updateroom/<int:pk>', views.AdminRoomUpdateView.as_view(), name="updateroom"),
    path('deleteroom/<int:pk>', views.AdminRoomDeleteView.as_view(), name="deleteroom"),
    path('customerlist/', views.AdminCustomerListView.as_view(), name="customerlist"),
    path('customerupdate/<int:pk>', views.AdmincustomerUpdateView.as_view(), name="customerupdate"),
    path('customerdelete/<int:pk>', views.AdminCustomerDeleteView.as_view(), name="customerdelete"),
    path('adminbookinglist/', views.AdminBookingList.as_view(), name="adminbookinglist"),
    path('admininvoice/', views.AdminBookingInvoiceList.as_view(), name="admininvoice"),
]

myadmin/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    MALE = 'MALE'
    FEMALE = 'FEMALE'

    GENDER_CHOICES = (
        ('MALE', MALE),
        ('FEMALE', FEMALE)
    )

    gender = models.CharField(max_length=70, choices=GENDER_CHOICES, null=True, blank=True)
    phone_no = models.CharField(max_length=70, null=True, blank=True)
    street = models.CharField(max_length=70, null=True, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    address = models.CharField(max_length=70, null=True, blank=True)
    city = models.CharField(max_length=70, null=True, blank=True)
    state = models.CharField(max_length=70, null=True, blank=True)
    pin_code = models.CharField(max_length=70, null=True, blank=True)
    country = models.CharField(max_length=70, null=True, blank=True)
    image = models.ImageField(upload_to='upload/', max_length=255, null=True, default=None)

myadmin/forms.py
from django import forms
from myadmin.models import User
from django.contrib.auth.forms import UserCreationForm
from hotel.models import *

class SignupForm(UserCreationForm):
    first_name = forms.CharField(max_length=70, required=False)
    last_name = forms.CharField(max_length=70, required=False)
    email = forms.EmailField(max_length=70, help_text="Enter a valid email address")
    phone_no = forms.CharField(max_length=70, help_text="Enter a valid phone No")
    username = forms.CharField(max_length=70, required=False)
    

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'phone_no',
            'password1',
            'password2',
            'gender',
            'birth_date',
            'address',
            'street',
            'city',
            'state',
            'country',
            'pin_code',
        ]
        widgets = {
            "birth_date":forms.DateInput(attrs={'type':'date'}),               
        }


class UserLoginForm(forms.ModelForm):
    username = forms.CharField(max_length=70, required=True, widget=forms.TextInput)
    password = forms.CharField(max_length=70, required=True, widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']



class AdminProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'phone_no',
            'gender',
            'birth_date',
            'address',
            'city',
            'state',
            'pin_code',
            'country',
            'image',
        ]
 
        widgets = {
            "birth_date": forms.DateInput(attrs={'type':'date'}),
        }

class AdminRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['is_available']

myadmin/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, UpdateView, DetailView, CreateView, DeleteView, ListView
from django.contrib.auth.views import LoginView, AuthenticationForm, LogoutView
from django.contrib.auth import authenticate, login, logout
from .models import *
from .forms import *
from django .urls import reverse_lazy
from django.contrib import messages
from hotel.models import *
from django.db.models import Q




# Create your views here.

#<-----------------------------------------------------Myadmin Dashboard Template View Starts from here------------------------->

class IndexTemplateView(TemplateView):
    template_name = 'myadmin/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_booking'] = Booking.objects.count()
        context['total_room'] = Room.objects.count()
        context['total_customer'] = User.objects.filter(is_active=True, is_staff=False).count()
        # context['total_customer'] = User.objects.exclude(is_staff=True).count()
        return context

#<--------------------------------------------------------Myadmin Profile View Starts from here--------------------------------->

class AdminProfile(UpdateView):
    model = User
    form_class = AdminProfileForm
    template_name = 'myadmin/profile.html'
    success_url = '/myadmin/'
    

#<-------------------------------------------------------Signup View Starts from here------------------------------------------->

class SignUpView(CreateView):
       form_class = SignupForm
       template_name = 'myadmin/signup.html'
       success_url = reverse_lazy("myadmin:userlogin")


#<---------------------------------------------------------User Login View Starts from here-------------------------------------->

class UserLogin(LoginView):
    Authentication_Form = UserLoginForm
    template_name = 'myadmin/login.html'


#<----------------------------------------------------------Logout View starts from here----------------------------------------->

class Logout(LogoutView):
    def get(self, request):
        logout(self.request)
        return redirect('myadmin:userlogin')


#<------------------------------------------------------------Room Details are starts here----------------------------------------->

class AdminRoomCreate(CreateView):
    model = Room
    form_class = AdminRoomForm
    template_name = 'myadmin/addroom.html'
    success_url = reverse_lazy('myadmin:roomlist')

    def form_valid(self, form):
        room_obj = form.save()
        ri = self.request.FILES.getlist('image')
        for f in ri:
            RoomImage.objects.update_or_create(image=f, room=room_obj)
            return super().form_valid(form)

#<--------------------------------Admin Room List View Start From here------------------------------------------------------------->

class AdminRoomList(ListView):
    model = Room
    template_name = 'myadmin/roomlist.html'

    # def get_queryset(self):
    #     queryset= super().get_queryset()
    #     room_category = self.request.GET.get('room_category')

    #     if room_category:
    #         queryset = queryset.filter(Q(room_categories__icontains=room_category))
    #     return queryset 

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search_query')

        if search_query:
            # Try to cast the search query to an integer (room number)
            try:
                room_no = int(search_query)
                queryset = queryset.filter(Q(room_no=room_no))
            except ValueError:
                # If it's not a valid integer, search by room category
                queryset = queryset.filter(Q(room_categories__icontains=search_query))

        return queryset

    

    


#<----------------------------------Admin Room Update View Start from here--------------------------->

class AdminRoomUpdateView(UpdateView):
    model = Room
    form_class = AdminRoomForm
    template_name = 'myadmin/updateroom.html'
    success_url = reverse_lazy('myadmin:roomlist')


    def form_valid(self, form):
        room_obj = form.save()
        ri = self.request.FILES.getlist('image')
        for f in ri:
            RoomImage.objects.update_or_create(image=f, room=room_obj)
            return super().form_valid(form)

#<-----------------------------------Admin Room Delete View start from here------------------------------>

class AdminRoomDeleteView(DeleteView):
    model = Room
    template_name = 'myadmin/deleteroom.html'
    success_url = reverse_lazy("myadmin:roomlist")

#<-----------------------------------Admin Customer List View Start from here----------------------------->

class AdminCustomerListView(ListView):
    model = User
    template_name = 'myadmin/customerdetail.html'

    # def get_queryset(self):
    #     qs = super().get_queryset()
    #     qs = qs.filter(is_superuser=False)
    #     return qs    

    def get_queryset(self):
        qs = super().get_queryset().filter(is_superuser=False)
        search_query = self.request.GET.get('search', None)

        if search_query:
            qs = qs.filter(
                Q(first_name__icontains=search_query) | 
                Q(phone_no__icontains=search_query) |
                Q(city__icontains=search_query) |
                Q(state__icontains=search_query)
            )
        return qs

#<------------------------------------Admin Customer Update view Starts from here----------------------------->

class AdmincustomerUpdateView(UpdateView):
    model = User
    form_class = AdminProfileForm
    template_name = 'myadmin/customerupdate.html'
    success_url = reverse_lazy("myadmin:customerlist")

#<----------------------------------------Admin Customer DeleteView Starts from here----------------------------->

class AdminCustomerDeleteView(DeleteView):
    model = User
    template_name = 'myadmin/customerdelete.html'
    success_url = reverse_lazy("myadmin:customerlist")

#<---------------------------------------------Admin Booking List View Starts from here--------------------------->

class AdminBookingList(ListView):
    model = Payment
    template_name = 'myadmin/adminbookinglist.html'

    def get_queryset(self):
      qs = self.request.GET.get('search', '')

      queryset = Payment.objects.filter(
        Q(user__first_name__icontains=qs) |
        Q(user__email__icontains=qs) |
        Q(user__phone_no__icontains=qs) |
        Q(booking__room__room_categories__icontains=qs) |
        Q(booking__room__room_no__icontains=qs)
      )
      return queryset


#<-----------------------------------------------------Admin Booking Invoice List Starts from here------------------------------>

class AdminBookingInvoiceList(ListView):
    model = Payment
    template_name = 'myadmin/adminbookinginvoice.html'

    def get_queryset(self):
      qs = self.request.GET.get('search', '')

      queryset = Payment.objects.filter(
        Q(user__first_name__icontains=qs) |
        Q(user__email__icontains=qs) |
        Q(user__phone_no__icontains=qs) |
        Q(booking__room__room_categories__icontains=qs) |
        Q(booking__room__room_no__icontains=qs)
      )
      return queryset

templates/myadmin/addroom.html
{% extends 'myadmin/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title mt-5">Add Room</h3> </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form class="add room" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                    <div class="row formtype">
                        <div class="col-md-4">
                            <div class="form-group">
                                {{form.room_no | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.room_categories | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.bed_categories | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.room_stock | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.capacity | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                {{form.food_categgories | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                {{form.room_price | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div id="div_id_image", class="form-group">
                                <label for="id_image" class="requiredField">Room Image<span class="asteriskField">*</span>
                                </label>
                            <div>
                                <input type="file" name="image" multiple="True" class="mb-3 form-control-file" requiredid="id_image">
                            </div>
                        </div>
                        </div>
                    </div>
                        <a href="{% url 'myadmin:roomlist' %}"><button type="submit" class="btn btn-primary buttonedit ml-2">Save</button></a>
                        <a href="{% url 'myadmin:myadmin' %}"><button type="submit" class="btn btn-primary buttonedit">Cancel</button></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/myadmin/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
	<title>Hotel Dashboard Template</title>  
	<link rel="shortcut icon" type="image/x-icon" href="{% static 'myadmin/assets/img/favicon.png' %}">
	<link rel="stylesheet" href="{% static 'myadmin/assets/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'myadmin/assets/plugins/fontawesome/css/fontawesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'myadmin/assets/plugins/fontawesome/css/all.min.css' %}">
	<link rel="stylesheet" href="{% static 'myadmin/assets/css/feathericon.min.css' %}">
	<link rel="stylehseet" href="{% static 'myadmin/https://cdn.oesmith.co.uk/morris-0.5.1.css' %}">
	<link rel="stylesheet" href="{% static 'myadmin/assets/plugins/morris/morris.css' %}">
	<link rel="stylesheet" href="{% static 'myadmin/assets/css/style.css' %}"> </head>

<body>
	<div class="main-wrapper">
		<div class="header">
			<div class="header-left">
				<a href="index.html" class="logo"> <img src="{% static 'myadmin/assets/img/hotel_logo.png' %}" width="50" height="70" alt="logo"> <span class="logoclass">HOTEL</span> </a>
				<a href="index.html" class="logo logo-small"> <img src="{% static 'myadmin/assets/img/hotel_logo.png' %}" alt="Logo" width="30" height="30"> </a>
			</div>
			<a href="javascript:void(0);" id="toggle_btn"> <i class="fe fe-text-align-left"></i> </a>
			<a class="mobile_btn" id="mobile_btn"> <i class="fas fa-bars"></i> </a>
			<ul class="nav user-menu">
				<li class="nav-item dropdown has-arrow">
					<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <span class="user-img"><img class="rounded-circle" src="{% static 'myadmin/assets/img/profiles/avatar-01.jpg' %}" width="31" alt="Soeng Souy"></span> </a>
					<div class="dropdown-menu">
						<div class="user-header">
							<div class="avatar avatar-sm"> <img src="{% static 'myadmin/assets/img/profiles/avatar-01.jpg' %}" alt="User Image" class="avatar-img rounded-circle"> </div>
							<div class="user-text">
								<h6>Sarthak Shah</h6>
								<p class="text-muted mb-0">Administrator</p>
							</div>
						</div> <a class="dropdown-item" href="{% url 'myadmin:profile' user.id %}">My Profile</a>
                        <a class="dropdown-item" href="{% url 'myadmin:userlogin' %}">Logout</a> </div>
				</li>
			</ul>
		</div>
		<div class="sidebar" id="sidebar">
			<div class="sidebar-inner slimscroll">
				<div id="sidebar-menu" class="sidebar-menu">
					<ul>
						<li class="active"> <a href="{% url 'myadmin:myadmin' %}"><i class="fas fa-tachometer-alt"></i> <span>Dashboard</span></a> </li>
						<li class="list-divider"></li>
						<li class="submenu"> <a href="#"><i class="fas fa-suitcase"></i> <span> Booking </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'myadmin:adminbookinglist' %}"> All Booking </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-user"></i> <span> Customers </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'myadmin:customerlist' %}"> All customers </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="fas fa-key"></i> <span> Rooms </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'myadmin:roomlist' %}">All Rooms </a></li>
								<li><a href="{% url 'myadmin:addroom' %}"> Add Rooms </a></li>
							</ul>
						</li>
						<li class="submenu"> <a href="#"><i class="far fa-money-bill-alt"></i> <span> Accounts </span> <span class="menu-arrow"></span></a>
							<ul class="submenu_class" style="display: none;">
								<li><a href="{% url 'myadmin:admininvoice' %}">Invoices </a></li>
							</ul>
						</li>
							</ul>
						</li>
					</ul>
				</div>
			</div>
		</div>
{% block content %}

{% endblock %}
<script data-cfasync="false" src="{% static 'myadmin/../../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script>
	<script src="{% static 'myadmin/assets/js/jquery-3.5.1.min.js' %}"></script>
	<script src="{% static 'myadmin/assets/js/popper.min.js' %}"></script>
	<script src="{% static 'myadmin/assets/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'myadmin/assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
	<script src="{% static 'myadmin/assets/plugins/raphael/raphael.min.js' %}"></script>
	<script src="{% static 'myadmin/assets/plugins/morris/morris.min.js' %}"></script>
	<script src="{% static 'myadmin/assets/js/chart.morris.js' %}"></script>
	<script src="{% static 'myadmin/assets/js/script.js' %}"></script>
</body>
</html>

templates/myadmin/customerdetail.html
{% extends 'myadmin/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="mt-5">
                        <h4 class="card-title float-left mt-2">Customer Details</h4></div>
                        <form class="form-inline my-2 my-lg-0" method="GET">
                            <div class="col-4 text-right">
                                <input class="form-control mr-sm-2" type="text" name="search" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                        </div>
                </div>
            </div>
        </div>
<div class="row">
    <div class="col-sm-12">
        <div class="card card-table">
            <div class="card-body booking_card">
                <div class="table-responsive">
                    <table class="datatable table table-stripped table table-hover table-center mb-1">
                        <thead class="table-primary">
                            <tr>
                                <th>Customer ID</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Mobile No</th>
                                <th>Birth Date</th>
                                <th>Gender</th>
                                <th>Address</th>
                                <th>City</th>
                                <th>State</th>
                                <th>Country</th>
                                <th>Pin Code</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for customer in object_list %}
                            <tr>
                                <td>{{customer.id}}</td>
                                <td>{{customer.first_name}} {{customer.last_name}}</td>
                                <td>{{customer.email}}</td>
                                <td>{{customer.phone_no}}</td>
                                <td>{{customer.birth_date}}</td>
                                <td>{{customer.gender}}</td>
                                <td>{{customer.address}}</td>
                                <td>{{customer.city}}</td>
                                <td>{{customer.state}}</td>
                                <td>{{customer.country}}</td>
                                <td>{{customer.pin_code}}</td>
                                <td>
                                    <a href="{% url 'myadmin:customerupdate' customer.id %}"><button type="submit" class="btn btn-warning mr-2">Update</button></a>
                                    <a href="{% url 'myadmin:customerdelete' customer.id %}"><button type="submit" class="btn btn-danger">Delete</button></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/myadmin/roomlist.html
{% extends 'myadmin/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <div class="mt-5">
                        <h4 class="card-title float-left mt-2">All Rooms</h4> <a href="{% url 'myadmin:addroom' %}" class="btn btn-primary float-right veiwbutton">Add Room</a> </div>
                        <form class="form-inline my-2 my-lg-0" method="GET">
                            <div class="col-4 text-right">
                                <input class="form-control mr-sm-2" type="text" name="search_query" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                        </div>
                        
                </div>
            </div>
        </div>
<div class="row">
    <div class="col-sm-12">
        <div class="card card-table">
            <div class="card-body booking_card">
                <div class="table-responsive">
                    <table class="datatable table table-stripped table table-hover table-center mb-1">
                        <thead class="table-primary">
                            <tr>
                                <th>Room ID</th>
                                <th>Room No</th>
                                <th>Room Image</th>
                                <th>Room Categories</th>
                                <th>Bed Categories</th>
                                <th>Room Stock</th>
                                <th>Food Categories</th>
                                <th>Capacity</th>
                                <th>Room Price</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for room in object_list %}
                            <tr>
                                <td>{{room.id}}</td>
                                <td>{{room.room_no}}</td>
                                <td><img src="/media/{{room.roomimage.last.image}}"style="height: 70px; width: 70px; border-radius: 10px";></td>
                                <td>{{room.room_categories}}</td>
                                <td>{{room.bed_categories}}</td>
                                <td>{{room.room_stock}}</td>
                                <td>{{room.food_categgories}}</td>
                                <td>{{room.capacity}}</td>
                                <td>{{room.room_price}}</td>
                                <td>
                                    <a href="{% url 'myadmin:updateroom' room.id %}"><button type="submit" class="btn btn-warning">Update</button></a>
                                    <a href="{% url 'myadmin:deleteroom' room.id %}"><button type="submit" class="btn btn-danger">Delete</button></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
{% endblock %}

templates/myadmin/updateroom.html
{% extends 'myadmin/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="page-wrapper">
    <div class="content container-fluid">
        <div class="page-header">
            <div class="row align-items-center">
                <div class="col">
                    <h3 class="page-title mt-5">Add Room</h3> </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <form class="add room" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                    <div class="row formtype">
                        <div class="col-md-4">
                            <div class="form-group">
                                {{form.room_no | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.room_categories | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.bed_categories | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.room_stock | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                               {{form.capacity | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                {{form.food_categgories | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div class="form-group">
                                {{form.room_price | as_crispy_field}}
                            </div>
                        </div>

                        <div class="col-md-4">
                            <div id="div_id_image", class="form-group">
                                <label for="id_image" class="requiredField">Room Image<span class="asteriskField">*</span>
                                </label>
                            <div>
                                <input type="file" name="image" multiple="True" class="mb-3 form-control-file" requiredid="id_image">
                            </div>
                        </div>
                        </div>
                    </div>
                        <a href="{% url 'myadmin:roomlist' %}"><button type="submit" class="btn btn-primary buttonedit ml-2">Save</button></a>
                        <a href="{% url 'myadmin:myadmin' %}"><button type="button" class="btn btn-primary buttonedit">Cancel</button></a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}